/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.gamestore.app;

import cat.uvic.teknos.m06.gamestore.domain.LinkedList;

import static cat.uvic.teknos.m06.gamestore.utilities.StringUtils.join;
import static cat.uvic.teknos.m06.gamestore.utilities.StringUtils.split;
import static cat.uvic.teknos.m06.gamestore.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

import java.sql.DriverManager;
import java.sql.SQLException;

public class App {
    public static void main(String[] args) throws SQLException {
        try(var connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/gamestore", "root", null))
        {
            connection.setAutoCommit(false);

            var preparedStatement = connection.prepareStatement("select emp_id, full_name from employees where emp_id = ?");

            preparedStatement.setInt(1,Integer.parseInt(args[0]));

            var resultSet = preparedStatement.executeQuery();

            /* var statement = connection.createStatement();

            statement.executeUpdate("insert into employees values(2,'Cathy Vipi', 'm')");

            var resultSet = statement.executeQuery("select emp_id, full_name from employees where emp_id = 2");

             */

            while (resultSet.next()){
                System.out.println("emp_id:"+ resultSet.getInt("emp_id")
                        + ", Full_name: "+ resultSet.getString("full_name"));
            }
            connection.commit();
        }
    }
}
