/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.gamestore.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
